# Generated by Django 3.1.4 on 2020-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
