# Generated by Django 3.1.4 on 2020-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20201209_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='urlornot',
            field=models.BooleanField(default=False),
        ),
    ]
