# Generated by Django 3.1.4 on 2020-12-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_auto_20201209_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='urlornot',
            new_name='url',
        ),
    ]
